export const standings = [
  {
    rank: 1,
    team: {
      id: 50,
      name: 'Manchester City',
      logo: 'https://media.api-sports.io/football/teams/50.png',
    },
    points: 71,
    goalsDiff: 43,
    group: 'Premier League',
    form: 'WWLWW',
    status: 'same',
    description: 'Promotion - Champions League (Group Stage)',
    all: {
      played: 30,
      win: 22,
      draw: 5,
      lose: 3,
      goals: {
        for: 64,
        against: 21,
      },
    },
    home: {
      played: 16,
      win: 12,
      draw: 2,
      lose: 2,
      goals: {
        for: 36,
        against: 13,
      },
    },
    away: {
      played: 14,
      win: 10,
      draw: 3,
      lose: 1,
      goals: {
        for: 28,
        against: 8,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 2,
    team: {
      id: 33,
      name: 'Manchester United',
      logo: 'https://media.api-sports.io/football/teams/33.png',
    },
    points: 57,
    goalsDiff: 24,
    group: 'Premier League',
    form: 'WWDDW',
    status: 'same',
    description: 'Promotion - Champions League (Group Stage)',
    all: {
      played: 29,
      win: 16,
      draw: 9,
      lose: 4,
      goals: {
        for: 56,
        against: 32,
      },
    },
    home: {
      played: 14,
      win: 7,
      draw: 3,
      lose: 4,
      goals: {
        for: 29,
        against: 19,
      },
    },
    away: {
      played: 15,
      win: 9,
      draw: 6,
      lose: 0,
      goals: {
        for: 27,
        against: 13,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 3,
    team: {
      id: 46,
      name: 'Leicester',
      logo: 'https://media.api-sports.io/football/teams/46.png',
    },
    points: 56,
    goalsDiff: 21,
    group: 'Premier League',
    form: 'WWDLW',
    status: 'same',
    description: 'Promotion - Champions League (Group Stage)',
    all: {
      played: 29,
      win: 17,
      draw: 5,
      lose: 7,
      goals: {
        for: 53,
        against: 32,
      },
    },
    home: {
      played: 14,
      win: 7,
      draw: 1,
      lose: 6,
      goals: {
        for: 25,
        against: 19,
      },
    },
    away: {
      played: 15,
      win: 10,
      draw: 4,
      lose: 1,
      goals: {
        for: 28,
        against: 13,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 4,
    team: {
      id: 49,
      name: 'Chelsea',
      logo: 'https://media.api-sports.io/football/teams/49.png',
    },
    points: 51,
    goalsDiff: 19,
    group: 'Premier League',
    form: 'DWWDD',
    status: 'same',
    description: 'Promotion - Champions League (Group Stage)',
    all: {
      played: 29,
      win: 14,
      draw: 9,
      lose: 6,
      goals: {
        for: 44,
        against: 25,
      },
    },
    home: {
      played: 14,
      win: 7,
      draw: 5,
      lose: 2,
      goals: {
        for: 25,
        against: 11,
      },
    },
    away: {
      played: 15,
      win: 7,
      draw: 4,
      lose: 4,
      goals: {
        for: 19,
        against: 14,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 5,
    team: {
      id: 48,
      name: 'West Ham',
      logo: 'https://media.api-sports.io/football/teams/48.png',
    },
    points: 49,
    goalsDiff: 10,
    group: 'Premier League',
    form: 'DLWLW',
    status: 'same',
    description: 'Promotion - Europa League (Group Stage)',
    all: {
      played: 29,
      win: 14,
      draw: 7,
      lose: 8,
      goals: {
        for: 45,
        against: 35,
      },
    },
    home: {
      played: 15,
      win: 8,
      draw: 4,
      lose: 3,
      goals: {
        for: 26,
        against: 18,
      },
    },
    away: {
      played: 14,
      win: 6,
      draw: 3,
      lose: 5,
      goals: {
        for: 19,
        against: 17,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 6,
    team: {
      id: 47,
      name: 'Tottenham',
      logo: 'https://media.api-sports.io/football/teams/47.png',
    },
    points: 48,
    goalsDiff: 19,
    group: 'Premier League',
    form: 'WLWWW',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 14,
      draw: 6,
      lose: 9,
      goals: {
        for: 49,
        against: 30,
      },
    },
    home: {
      played: 14,
      win: 7,
      draw: 3,
      lose: 4,
      goals: {
        for: 25,
        against: 14,
      },
    },
    away: {
      played: 15,
      win: 7,
      draw: 3,
      lose: 5,
      goals: {
        for: 24,
        against: 16,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 7,
    team: {
      id: 40,
      name: 'Liverpool',
      logo: 'https://media.api-sports.io/football/teams/40.png',
    },
    points: 46,
    goalsDiff: 12,
    group: 'Premier League',
    form: 'WLLWL',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 13,
      draw: 7,
      lose: 9,
      goals: {
        for: 48,
        against: 36,
      },
    },
    home: {
      played: 15,
      win: 7,
      draw: 2,
      lose: 6,
      goals: {
        for: 22,
        against: 18,
      },
    },
    away: {
      played: 14,
      win: 6,
      draw: 5,
      lose: 3,
      goals: {
        for: 26,
        against: 18,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 8,
    team: {
      id: 45,
      name: 'Everton',
      logo: 'https://media.api-sports.io/football/teams/45.png',
    },
    points: 46,
    goalsDiff: 3,
    group: 'Premier League',
    form: 'LLWWW',
    status: 'same',
    description: null,
    all: {
      played: 28,
      win: 14,
      draw: 4,
      lose: 10,
      goals: {
        for: 40,
        against: 37,
      },
    },
    home: {
      played: 14,
      win: 5,
      draw: 2,
      lose: 7,
      goals: {
        for: 19,
        against: 22,
      },
    },
    away: {
      played: 14,
      win: 9,
      draw: 2,
      lose: 3,
      goals: {
        for: 21,
        against: 15,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 9,
    team: {
      id: 42,
      name: 'Arsenal',
      logo: 'https://media.api-sports.io/football/teams/42.png',
    },
    points: 42,
    goalsDiff: 8,
    group: 'Premier League',
    form: 'DWDWL',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 12,
      draw: 6,
      lose: 11,
      goals: {
        for: 40,
        against: 32,
      },
    },
    home: {
      played: 14,
      win: 6,
      draw: 3,
      lose: 5,
      goals: {
        for: 18,
        against: 15,
      },
    },
    away: {
      played: 15,
      win: 6,
      draw: 3,
      lose: 6,
      goals: {
        for: 22,
        against: 17,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 10,
    team: {
      id: 66,
      name: 'Aston Villa',
      logo: 'https://media.api-sports.io/football/teams/66.png',
    },
    points: 41,
    goalsDiff: 9,
    group: 'Premier League',
    form: 'LDDLW',
    status: 'same',
    description: null,
    all: {
      played: 28,
      win: 12,
      draw: 5,
      lose: 11,
      goals: {
        for: 39,
        against: 30,
      },
    },
    home: {
      played: 13,
      win: 5,
      draw: 2,
      lose: 6,
      goals: {
        for: 20,
        against: 18,
      },
    },
    away: {
      played: 15,
      win: 7,
      draw: 3,
      lose: 5,
      goals: {
        for: 19,
        against: 12,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 11,
    team: {
      id: 63,
      name: 'Leeds',
      logo: 'https://media.api-sports.io/football/teams/63.png',
    },
    points: 39,
    goalsDiff: -2,
    group: 'Premier League',
    form: 'WDLLW',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 12,
      draw: 3,
      lose: 14,
      goals: {
        for: 45,
        against: 47,
      },
    },
    home: {
      played: 14,
      win: 5,
      draw: 3,
      lose: 6,
      goals: {
        for: 19,
        against: 17,
      },
    },
    away: {
      played: 15,
      win: 7,
      draw: 0,
      lose: 8,
      goals: {
        for: 26,
        against: 30,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 12,
    team: {
      id: 52,
      name: 'Crystal Palace',
      logo: 'https://media.api-sports.io/football/teams/52.png',
    },
    points: 37,
    goalsDiff: -16,
    group: 'Premier League',
    form: 'WLDDW',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 10,
      draw: 7,
      lose: 12,
      goals: {
        for: 31,
        against: 47,
      },
    },
    home: {
      played: 15,
      win: 5,
      draw: 5,
      lose: 5,
      goals: {
        for: 15,
        against: 21,
      },
    },
    away: {
      played: 14,
      win: 5,
      draw: 2,
      lose: 7,
      goals: {
        for: 16,
        against: 26,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 13,
    team: {
      id: 39,
      name: 'Wolves',
      logo: 'https://media.api-sports.io/football/teams/39.png',
    },
    points: 35,
    goalsDiff: -10,
    group: 'Premier League',
    form: 'LDLDW',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 9,
      draw: 8,
      lose: 12,
      goals: {
        for: 28,
        against: 38,
      },
    },
    home: {
      played: 14,
      win: 5,
      draw: 4,
      lose: 5,
      goals: {
        for: 15,
        against: 15,
      },
    },
    away: {
      played: 15,
      win: 4,
      draw: 4,
      lose: 7,
      goals: {
        for: 13,
        against: 23,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 14,
    team: {
      id: 41,
      name: 'Southampton',
      logo: 'https://media.api-sports.io/football/teams/41.png',
    },
    points: 33,
    goalsDiff: -15,
    group: 'Premier League',
    form: 'LLWLL',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 9,
      draw: 6,
      lose: 14,
      goals: {
        for: 36,
        against: 51,
      },
    },
    home: {
      played: 14,
      win: 5,
      draw: 2,
      lose: 7,
      goals: {
        for: 18,
        against: 18,
      },
    },
    away: {
      played: 15,
      win: 4,
      draw: 4,
      lose: 7,
      goals: {
        for: 18,
        against: 33,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 15,
    team: {
      id: 44,
      name: 'Burnley',
      logo: 'https://media.api-sports.io/football/teams/44.png',
    },
    points: 33,
    goalsDiff: -15,
    group: 'Premier League',
    form: 'WDDLD',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 8,
      draw: 9,
      lose: 12,
      goals: {
        for: 22,
        against: 37,
      },
    },
    home: {
      played: 15,
      win: 4,
      draw: 6,
      lose: 5,
      goals: {
        for: 12,
        against: 16,
      },
    },
    away: {
      played: 14,
      win: 4,
      draw: 3,
      lose: 7,
      goals: {
        for: 10,
        against: 21,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 16,
    team: {
      id: 51,
      name: 'Brighton',
      logo: 'https://media.api-sports.io/football/teams/51.png',
    },
    points: 32,
    goalsDiff: -4,
    group: 'Premier League',
    form: 'WWLLL',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 7,
      draw: 11,
      lose: 11,
      goals: {
        for: 32,
        against: 36,
      },
    },
    home: {
      played: 15,
      win: 2,
      draw: 7,
      lose: 6,
      goals: {
        for: 16,
        against: 19,
      },
    },
    away: {
      played: 14,
      win: 5,
      draw: 4,
      lose: 5,
      goals: {
        for: 16,
        against: 17,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 17,
    team: {
      id: 34,
      name: 'Newcastle',
      logo: 'https://media.api-sports.io/football/teams/34.png',
    },
    points: 28,
    goalsDiff: -20,
    group: 'Premier League',
    form: 'LDDDL',
    status: 'same',
    description: null,
    all: {
      played: 29,
      win: 7,
      draw: 7,
      lose: 15,
      goals: {
        for: 28,
        against: 48,
      },
    },
    home: {
      played: 14,
      win: 4,
      draw: 4,
      lose: 6,
      goals: {
        for: 17,
        against: 23,
      },
    },
    away: {
      played: 15,
      win: 3,
      draw: 3,
      lose: 9,
      goals: {
        for: 11,
        against: 25,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 18,
    team: {
      id: 36,
      name: 'Fulham',
      logo: 'https://media.api-sports.io/football/teams/36.png',
    },
    points: 26,
    goalsDiff: -15,
    group: 'Premier League',
    form: 'LLWLD',
    status: 'same',
    description: 'Relegation - Championship',
    all: {
      played: 30,
      win: 5,
      draw: 11,
      lose: 14,
      goals: {
        for: 23,
        against: 38,
      },
    },
    home: {
      played: 16,
      win: 2,
      draw: 4,
      lose: 10,
      goals: {
        for: 9,
        against: 23,
      },
    },
    away: {
      played: 14,
      win: 3,
      draw: 7,
      lose: 4,
      goals: {
        for: 14,
        against: 15,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 19,
    team: {
      id: 60,
      name: 'West Brom',
      logo: 'https://media.api-sports.io/football/teams/60.png',
    },
    points: 18,
    goalsDiff: -37,
    group: 'Premier League',
    form: 'LDLWD',
    status: 'same',
    description: 'Relegation - Championship',
    all: {
      played: 29,
      win: 3,
      draw: 9,
      lose: 17,
      goals: {
        for: 20,
        against: 57,
      },
    },
    home: {
      played: 15,
      win: 2,
      draw: 5,
      lose: 8,
      goals: {
        for: 9,
        against: 33,
      },
    },
    away: {
      played: 14,
      win: 1,
      draw: 4,
      lose: 9,
      goals: {
        for: 11,
        against: 24,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
  {
    rank: 20,
    team: {
      id: 62,
      name: 'Sheffield Utd',
      logo: 'https://media.api-sports.io/football/teams/62.png',
    },
    points: 14,
    goalsDiff: -34,
    group: 'Premier League',
    form: 'LLWLL',
    status: 'same',
    description: 'Relegation - Championship',
    all: {
      played: 29,
      win: 4,
      draw: 2,
      lose: 23,
      goals: {
        for: 16,
        against: 50,
      },
    },
    home: {
      played: 15,
      win: 3,
      draw: 1,
      lose: 11,
      goals: {
        for: 10,
        against: 22,
      },
    },
    away: {
      played: 14,
      win: 1,
      draw: 1,
      lose: 12,
      goals: {
        for: 6,
        against: 28,
      },
    },
    update: '2021-03-21T00:00:00+00:00',
  },
];
